version: '3.8'

services:
  admin-backend:
    build: .
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=cs-chatbot-secret-key
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/auth/login"]
      interval: 30s
      timeout: 10s
      retries: 3